package hello;
// Generated 29-Aug-2017 14:34:31 by Hibernate Tools 5.2.3.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private long messageId;
     private Messages messages;
     private String messageText;
     private Set messageses = new HashSet(0);

    public Messages() {
    }

	
    public Messages(long messageId) {
        this.messageId = messageId;
    }
    public Messages(long messageId, Messages messages, String messageText, Set messageses) {
       this.messageId = messageId;
       this.messages = messages;
       this.messageText = messageText;
       this.messageses = messageses;
    }
   
    public long getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(long messageId) {
        this.messageId = messageId;
    }
    public Messages getMessages() {
        return this.messages;
    }
    
    public void setMessages(Messages messages) {
        this.messages = messages;
    }
    public String getMessageText() {
        return this.messageText;
    }
    
    public void setMessageText(String messageText) {
        this.messageText = messageText;
    }
    public Set getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set messageses) {
        this.messageses = messageses;
    }




}


